name: 'Label Actions'

# Based on https://github.com/marketplace/actions/label-actions#examples

on:
  issues:
    types: [labeled, unlabeled]

permissions:
  contents: read
  issues: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/label-actions@v2
